# Generated by Django 5.0.7 on 2024-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="price",
            field=models.SmallIntegerField(),
        ),
    ]
