# Generated by Django 5.0.7 on 2024-07-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sales_rest",
            "0002_alter_customer_address_alter_customer_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
