# Generated by Django 5.0.7 on 2024-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0004_alter_sale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=250),
        ),
    ]
