# Generated by Django 5.0.7 on 2024-07-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_rest", "0005_alter_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=25),
        ),
    ]
