# Generated by Django 5.0.7 on 2024-07-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0002_alter_automobilevo_vin"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="vip",
            field=models.CharField(default=False, max_length=20),
        ),
    ]
