# Generated by Django 5.0.7 on 2024-07-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0004_rename_appointment_appointments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="vip",
            field=models.BooleanField(default=False),
        ),
    ]
