# Generated by Django 5.0.7 on 2024-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0005_alter_appointments_vip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="vin",
            field=models.CharField(max_length=200),
        ),
    ]
