# Generated by Django 5.0.7 on 2024-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_rest", "0006_alter_appointments_vin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="vip",
            field=models.CharField(default="No", editable=False, max_length=5),
        ),
    ]
